# Project information
site_name: 'Loki Docs'
site_url: 'https://loki-project.github.io/loki-docs/'

# Repository
repo_name: 'lokidocs'
repo_url: 'https://github.com/loki-project/loki-docs'



# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
     accent: 'green'
  direction: 'ltr'
  feature:
    tabs: true     

  font:
    title: 'Proxima Nova'
    text: 'Roboto Regular'
    code: 'Roboto'
  favicon: 'Loki_favicon32x32.png'
  logo: 'logo.svg'

nav:
- 'Home': 'index.md'
- 'Introduction': 'Introduction/LokiNetwork.md'
- 'Getting Started': 'Introduction/GettingStarted.md'
- 'FAQ': 'FAQ.md'

- Wallets: 
  - 'Overview' : 'Wallets/WalletsOverview.md'
  - 'What wallet to use?' : 'Wallets/WhatWalletToUse.md'

  - Addresses:
    - 'Main Address': 'Wallets/Addresses/MainAddress.md'
    - 'Sub Address': 'Wallets/Addresses/SubAddress.md'
    - 'Integrated Address': 'Wallets/Addresses/IntegratedAddress.md'
#  - Web Wallet (LokiLocker): 
#      - 'Troubleshooting Web Wallet' : 'Wallets/WebWallet/TroubleshootWebWallet.md'
#      - Guides:
#        - 'to be added': 'Wallets/WebWallet/placeholder.md'
  - 'Multsignature': 'Wallets/Multisignature.md'

  - Guides: 
        - 'Gui Setup': 'Wallets/GuiWallet/loki-gui-guide.md'
        - 'Gui Staking Guide': 'ServiceNodes/GUIStakingGuide.md'
        - 'Mobile Wallet Restore': 'Wallets/MobileWallet/RestoreMobileWalletGuide.md'
        - 'CLI Mac Setup': 'Wallets/CliWallet/loki-wallet-cliMacSetup.md'
        - 'CLI Wallet Commands': 'Wallets/CliWallet/WalletCommands.md'
        - 'CLI Restoring Wallet from Seed': 'Wallets/CliWallet/WalletRestoreSeed.md'
        - 'CLI Restoring Wallet from Keys': 'Wallets/CliWallet/WalletRestoreKeys.md'
        - Multisig:
           - '2/2 Multisig': 'Wallets/CliWallet/2of2Multisig.md'
           - '2/3 Multisig': 'Wallets/CliWallet/2of3Multisig.md'
           - 'M/N Multsig': 'Wallets/CliWallet/MofNMultisig.md'



- Mining:
    - 'Overview': 'Mining/MiningOverview.md'
    - 'ASIC Resistance': 'Mining/ASICResistance.md'
#    - Guides:
#      - 'XMR-Stak Mining': 'Mining/XMR-StakGuide.md'
#      - 'XMR-Stak Linux Mining': 'Mining/XMR-Stak-Linux-Guide.md'
#      - 'XMRig Mining': 'Mining/XMRig-Guide.md'
#      - 'Mining With a SBC': 'Mining/Mining-With-SBC.md'


- Service Nodes:
    - 'Overview': 'ServiceNodes/SNOverview.md'
    - 'Service Node Functions': 'ServiceNodes/ServiceNodeFunctions.md'
    - 'Staking Requirement': 'ServiceNodes/StakingRequirement.md'
    - 'Infinite Staking Primer': 'ServiceNodes/InfiniteStakingPrimer.md'
    - Guides:
      - 'Service Node Full Guide': 'ServiceNodes/SNFullGuide.md'
      - 'Service Node RPC Guide': 'Developer/SNRPCGuide.md'
      - 'Gui Staking Guide': 'ServiceNodes/GUIStakingGuide.md'

- Lokinet:
    - 'Overview': 'Lokinet/LokinetOverview.md'
    - 'Public Testing Overview': 'Lokinet/Guides/PublicTestingGuide.md'
    - 'SNApps': 'Lokinet/SNApps.md'
    - 'LLARP': 'Lokinet/LLARP.md'
    - 'Developers': 'Lokinet/DeveloperInfo.md'

    - Guides:
        - 'Installation': 'Lokinet/Guides/Install.md'
        - 'Accessing SNApps': 'Lokinet/Guides/AccessingSNApps.md'
        - 'Joining a Lokinet IRC Chat': 'Lokinet/Guides/LokinetIRC.md'
        - 'Hosting SNApps': 'Lokinet/Guides/HostingSNApps.md'
        - 'Route through Exit Node': 'Lokinet/Guides/RouteThroughExitNode.md'
        - 'Lokinet config files': 'Lokinet/Guides/LokinetConfig.md'
#        - 'Test Network Relay': 'Lokinet/Guides/TestNetRelay.md'
        - 'Exit Nodes': 'Lokinet/Guides/ExitNode.md'

- Advanced:
    - Developer:
       - 'Service Node RPC Guide': 'Developer/SNRPCGuide.md'
       - 'Daemon RPC Guide': 'Developer/DaemonRPCGuide.md'
       - 'Loki Wallet RPC Guide': 'Developer/WalletRPCGuide.md'
       - 'Developer FAQ': 'Developer/FAQ.md'

    - Loki Services:
       - 'Overview': 'LokiServices/LokiServicesOverview.md'
       - 'Messenger' : 'LokiServices/Messenger.md'
       - 'Blink': 'LokiServices/Blink.md'

    - Attack Prevention:
       - 'Denial of Service Attacks': 'Advanced/DenialofServiceAttacks.md'
       - 'IP and Packet Blocking': 'Advanced/IPandPacketBlocking.md'
       - 'Swarm Flagging': 'Advanced/SwarmFlagging.md'
    
    - Contributing:
       - 'How to Contribute to LokiDocs': 'Contributing/HowToContributeToLokiDocs.md'
       - 'Vulnerability Response': 'Contributing/VULNERABILITY_RESPONSE_LOKI.md'
       - 'Github Issue Template Example': 'Contributing/Issue_Template.md'

    - Governance:
       - 'Overview': 'Governance/Governance.md'
       - 'The Loki Foundation': 'Governance/TheLokiFoundation.md'
       - 'Loki Funding System': 'Governance/LokiFundingSystem.md'

    - 'Technical Specs' : 'Advanced/TechnicalSpecs.md'
    - 'Cryptoeconomics' : 'Advanced/Cryptoeconomics.md'
    - 'Sybil Resistance' : 'Advanced/SybilResistance.md'
    - 'Dynamic Block Size': 'Advanced/DynamicBlockSize.md'
    - 'CryptoNote Elements': 'Advanced/CryptoNoteElements.md'
    - 'lokid' : 'Advanced/lokid.md'

    - Guides:
#        - 'Using Lokinet': 'Advanced/UsingLokinet.md'
        - 'Using Tor': 'Advanced/UsingTor.md'
        - 'Debugging': 'Advanced/Debugging.md'      
        - 'Accepting Loki for Merchants and Exchanges': 'Advanced/AcceptingLoki.md'

# Customization
extra_css:
  - CSS/style.css
  - CSS/font.css

extra_javascript:
  - JAVASCRIPT/links.js
  - JAVASCRIPT/style.js

extra:
  social:
    - type: 'github'
      link: 'https://github.com/loki-project'
    - type: 'twitter'
      link: 'https://twitter.com/loki_project'
    - type: 'telegram'
      link: 'https://t.me/LokiCommunity'
    - type: 'reddit'
      link: 'https://www.reddit.com/r/LokiProject'
    - type: 'youtube'
      link: 'https://www.youtube.com/lokinetwork'
    - type: 'facebook'
      link: 'https://www.facebook.com/LokiNetwork/'

# Google Analytics
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

